"""
创建示例几何文件
运行此脚本来生成测试数据
"""

from pathlib import Path
import json

# 创建目录
input_dir = Path("E:/DeepSeek_Work/test/input")
input_dir.mkdir(parents=True, exist_ok=True)

meshes_dir = Path("E:/DeepSeek_Work/test/meshes")
meshes_dir.mkdir(parents=True, exist_ok=True)

analyses_dir = Path("E:/DeepSeek_Work/test/analyses")
analyses_dir.mkdir(parents=True, exist_ok=True)

results_dir = Path("E:/DeepSeek_Work/test/results")
results_dir.mkdir(parents=True, exist_ok=True)

print("✅ 目录创建完成")

# 1. 创建简单的 CalculiX 输入文件（用于测试）
inp_file = analyses_dir / "test_cube.inp"

inp_content = """
** 测试立方体 - CalculiX 输入文件
** 自动生成

*HEADING
Test Cube Stress Analysis

** Generated by CAE Platform

*NODE, FILE=CUBE-NODES, NSET=NALL
1,0.0,0.0,0.0
2,10.0,0.0,0.0
3,10.0,10.0,0.0
4,0.0,10.0,0.0
5,0.0,0.0,10.0
6,10.0,0.0,10.0
7,10.0,10.0,10.0
8,0.0,10.0,10.0

*ELEMENT, TYPE=C3D8, ELSET=EALL
1,1,2,4,5,2,3,7,6
2,2,3,4,6,3,4,8,7

*MATERIAL, NAME=STEEL
*ELASTIC
210000.,0.3
*DENSITY
7.85E-9

*BOUNDARY
NSET,FIXED,1,1,3
1,2,5,6

*DLOAD
OP_NEW,SF,P1,1,3.0

*STEP, NLGEOM=NO, INC=10000
*STATIC
1.,1.,1E-07,1E-07

*NODE FILE, NSET=NALL
*EL FILE, ELSET=EALL
*EL PRINT, ELSET=EALL, FREQ=1
*NODE PRINT, NSET=NALL, FREQ=1
*END STEP
*END
"""

inp_file.write_text(inp_content)
print(f"✅ CalculiX 输入文件已创建: {inp_file}")

# 2. 创建任务配置文件（示例）
task_config = {
    "task_id": "task_001",
    "task_type": "stress",
    "geometry_file": "/app/test/input/test_cube.step",
    "mesh_file": "/app/test/meshes/test_cube.msh",
    "input_file": "/app/test/analyses/test_cube.inp",
    "output_file": "/app/test/results/test_cube.frd",
    "mesh_params": {
        "clmax": 2.0,
        "clmin": 0.5,
        "algorithm": "delaunay"
    },
    "material": {
        "elastic_modulus": 210000,
        "poisson_ratio": 0.3,
        "density": 7.85E-9
    },
    "boundary_conditions": {
        "fixed_nodes": [1, 2, 5, 6],
        "load": {
            "type": "pressure",
            "value": 3.0,
            "face": "SURFACE1"
        }
    }
}

config_file = input_dir / "task_config.json"
with open(config_file, 'w', encoding='utf-8') as f:
    json.dump(task_config, f, indent=2, ensure_ascii=False)

print(f"✅ 任务配置文件已创建: {config_file}")

# 3. 创建简单的说明文件
readme_file = input_dir / "README.txt"
readme_content = """
# 测试文件说明

## 文件列表

1. test_cube.inp - CalculiX 输入文件（立方体）
   - 8 个节点
   - 1 个单元（六面体）
   - 材料：钢材
   - 边界：底部固定，顶部加载

2. task_config.json - 任务配置示例
   - 包含网格参数
   - 材料属性
   - 边界条件

## 使用方法

### 方法 1：直接运行仿真（命令行）

```bash
# 进入 CalculiX 容器
docker exec -it cae_calculix bash

# 运行仿真
cd /app/test/analyses
ccx -i test_cube

# 查看结果
cat test_cube.out
```

### 方法 2：通过 Dashboard 提交任务

1. 访问 http://localhost:8501
2. 进入"任务管理"页面
3. 填写任务表单：
   - 任务类型：应力分析
   - 输入文件：/app/test/analyses/test_cube.inp
   - 网格参数：使用默认值
   - 提交任务

### 方法 3：通过 API 提交任务（如果有 API）

```python
import requests

# 提交任务
response = requests.post(
    "http://localhost:8000/api/v1/tasks",
    json={
        "task_type": "stress",
        "input_file": "/app/test/analyses/test_cube.inp",
        "parameters": {...}
    }
)

task_id = response.json()["task_id"]
print(f"任务 ID: {task_id}")
```

## 预期结果

- 节点数：8
- 单元数：1
- 最大应力：约 3.0 MPa
- 最大位移：约 0.0015 mm
- 计算时间：< 1 秒

## 查看结果

结果文件位置：
- test_cube.dat - 数值结果
- test_cube.frd - FRD 格式结果（用于可视化）

可视化方法：
1. 在 Dashboard 的"可视化"页面
2. 输入结果文件路径
3. 选择可视化类型
4. 生成云图

## 故障排除

如果任务失败：

1. 检查文件权限
```bash
docker exec -it cae_dashboard ls -la /app/test/analyses/
```

2. 检查 CalculiX 日志
```bash
docker logs cae_calculix --tail 50
```

3. 查看任务状态
```bash
# 访问 Flower
http://localhost:5555
```

4. 查看 Celery Worker 日志
```bash
docker logs cae_celery_worker --tail 50
```

## 下一步

1. 熟悉任务提交流程
2. 尝试不同的参数
3. 上传自己的几何文件
4. 探索可视化功能
5. 分析结果数据

---

如有问题，请参考 OPERATION_GUIDE.md
"""

readme_file.write_text(readme_content)
print(f"✅ 说明文件已创建: {readme_file}")

print("\n🎉 测试文件创建完成！")
print(f"\n📁 文件位置:")
print(f"  输入: {input_dir}")
print(f"  网格: {meshes_dir}")
print(f"  分析: {analyses_dir}")
print(f"  结果: {results_dir}")
print(f"\n📖 说明文件: {readme_file}")
print(f"\n🚀 下一步: 查看 OPERATION_GUIDE.md 了解如何开始第一个任务")
